### ISSUE TITLE
ippeveprinter.c fails to compile on Ubuntu 19.04 for  Openwrt make.

### ISSUE THREAD

**Issue by LondyGhost** [apple/cups#5627]
When I run make command, I get this error:

Making all in cups...
Making all in tools...
make[5]: Entering directory '/home/londy/lede/build_dir/target-mipsel_24kc_musl/cups-2.3rc1/tools'
Compiling ippeveprinter.c...
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<command-line>:0:0: note: this is the location of the previous definition
In file included from ippeveprinter.c:41:0:
/home/londy/lede/staging_dir/toolchain-mipsel_24kc_gcc-7.4.0_musl/include/sys/fcntl.h:1:2: warning: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Wcpp]
 #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
  ^~~~~~~
ippeveprinter.c: In function 'create_printer':
ippeveprinter.c:1561:57: error: 'securi' undeclared (first use in this function); did you mean 'uri'?
     fprintf(stderr, "printer-uri=\"%s\",\"%s\"\n", uri, securi);
                                                         ^~~~~~
                                                         uri
ippeveprinter.c:1561:57: note: each undeclared identifier is reported only once for each function it appears in
make[5]: *** [../Makedefs:271: ippeveprinter.o] Error 1
make[5]: Leaving directory '/home/londy/lede/build_dir/target-mipsel_24kc_musl/cups-2.3rc1/tools'
make[4]: *** [Makefile:42: all] Error 1
make[4]: Leaving directory '/home/londy/lede/build_dir/target-mipsel_24kc_musl/cups-2.3rc1'
make[3]: *** [Makefile:314: /home/londy/lede/build_dir/target-mipsel_24kc_musl/cups-2.3rc1/.built] Error 2
make[3]: Leaving directory '/home/londy/lede/feeds/cups/cups'
time: package/feeds/cups/cups/compile#0.37#0.11#0.45
make[2]: *** [package/Makefile:109: package/feeds/cups/cups/compile] Error 2
make[2]: Leaving directory '/home/londy/lede'
make[1]: *** [package/Makefile:103: /home/londy/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/londy/lede'
make: *** [/home/londy/lede/include/toplevel.mk:218：world] 错误 2

**Comment by rollednetlib** [comment]
Hey, a complete noob here. Just compiled this on my orange pi and ran into the same issue. Fixed it by changing the macro guard on line 1266-1269.
Can be fixed by adding securi[1024] after the `#endif`
` 1266 #ifdef HAVE_SSL
  1267                         securi[1024],   /* Secure printer URI */
  1268                         *uris[2],       /* All URIs */
  1269 #endif /* HAVE_SSL */
  1270                         securi[1024],   /* Secure printer URI */
`

**Comment by LondyGhost** [comment]
@rollednetlib Lines 1266-1269 are the same as you wrote, except for line 1270. The same error still occurred after I added it.

**Comment by michaelrsweet** [comment]
This is already fixed in Git master...
