### ISSUE TITLE
current svn does not compile with cups-1.1

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#1712]
Version: 8.15-current
CUPS.org User: genstef

When compiling espgs svn with cups-1.1:

pstoraster/gdevcups.c:3725: error: structure has no member named `cupsNumColors'

I think you might have overloooked that when coding. Judging by the svn log probably something like this should be there:

--- gdevcups.c  (revision 163)
+++ gdevcups.c  (working copy)
@@ -3722,7 +3722,11 @@
- to separate each chunked color as needed...
  */

+#ifdef CUPS_RASTER_SYNCv1
   bandbytes = cups->header.cupsBytesPerLine / cups->header.cupsNumColors;
+#elif
-  bandbytes = (cups->header.cupsWidth \* cups->header.cupsBitsPerColor + 7) / 8;
  +#endif /\* CUPS_RASTER_SYNCv1 */
  
  for (y = 0; y < cups->height; y ++)
  {
