### ISSUE TITLE
Compilation error on SuSE 8.1 (1.1.19 compiles)

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#534]
Version: 1.1.20
CUPS.org User: hk.alogis

I have to compile CUPS for SuSE 8.1:
## cups-1.1.20-source.tar.gz:
# tar -xvzf cups-1.1.20-source.tar.gz
# cd cups-1.1.20
# ./configure
# make

results in an error with 1.1.20 in file.c:
[...]
Compiling server.c...
Compiling file.c...
file.c: In function `cupsFileSeek':
file.c:554: structure has no member named`eof'
file.c: In function `cups_fill':
file.c:641: warning: unused variable`ptr'
file.c:642: warning: unused variable `end'
make[1]: **\* [file.o] Error 1
make: **\* [all] Error 1

the same seems to work with 1.1.19 (file.c), only producing warnings:

Compiling file.c...
file.c: In function `cups_fill':
file.c:639: warning: unused variable`ptr'
file.c:640: warning: unused variable `end'
Compiling filter.c...

Regards,
Holger Kipp
