### ISSUE TITLE
gziptoany filter doesn't compile in 1.2 CVS

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#410]
Version: 1.2-current
CUPS.org User: pipitas

This is a SuSE-8.2 system: 
- gcc (GCC) 3.3 20030226 (prerelease) (SuSE Linux)
- autoconf (GNU Autoconf) 2.57
- GNU Make 3.80

This is what I get when I try to compile 1.2 CVS:

[....]
Linking classes.cgi...
Linking jobs.cgi...
Linking printers.cgi...
Making all in filter...
Linking gziptoany...
/usr/lib/gcc-lib/i486-suse-linux/3.3/../../../crt1.o(.text+0x18): In function `_start':
: undefined reference to`main'
collect2: ld returned 1 exit status
make[1]: **\* [gziptoany] Fehler 1
make: **\* [all] Fehler 1

For the time being, I commented out the gziptoany target in the
Makefile of the filter directory....
