### ISSUE TITLE
CUPS 1.7.3 fails to compile with clang 3.4

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4421]
Version: 1.7-current
CUPS.org User: hussam

I have clang 3.4 and gcc 4.9 installed.
With clang 3.4, I get this build failure on linux (I noticed this because cups opts to use clang unless I specify CC=gcc / CXX=g++).
Compiling main.c...
main.c:437:5: warning: ignoring return value of function declared with warn_unused_result attribute
      [-Wunused-result]
    chdir("/");
    ^~~~~ ~~~
main.c:1529:5: error: non-void function 'systemd_checkin' should return a value [-Wreturn-type]
    return;
    ^
main.c:1533:5: error: non-void function 'systemd_checkin' should return a value [-Wreturn-type]
    return;
    ^
1 warning and 2 errors generated.
../Makedefs:248: recipe for target 'main.o' failed
make[1]: **\* [main.o] Error 1
Makefile:31: recipe for target 'all' failed
make: **\* [all] Error 1

Compiling with gcc 4.9 completes successfully.
