### ISSUE TITLE
cups-1.1.20 does not compile on FreeBSD-5.2.1-RELEASE

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#725]
Version: 1.1.20
CUPS.org User: cups.crel

Cups-1.1.20 will not compile on FreeBSD-5.2.1-RELEASE on
the i386 platform.  The first error was,

  ...
  Compiling image.c...
  Compiling raster.c...
  Linking libcupsimage.so.2...
  /usr/bin/ld: cannot find -lpng
  make[1]: **\* [libcupsimage.so.2] Error 1
  make: **\* [all] Error 1
  ...

configure found all the libraries and seemed to be
happy.  It's output looked like this,

  ...
  checking png.h usability... yes
  checking png.h presence... yes
  checking for png.h... yes
  checking for png_set_tRNS_to_alpha in -lpng... yes
  ...

I got past that problem by manually changing the line

  $(DSO) $(DSOFLAGS) -o $@ $(IMAGEOBJS) $(DSOLIBS) -lm
to
  $(DSO) $(LDFLAGS) $(DSOFLAGS) -o $@ $(IMAGEOBJS) $(DSOLIBS) -lm

under the libcupsimage.so.2 target in filters/Makefile.
Adding the $(LDFLAGS) variable fixed it.

Then, furthur into the compilation, I got the following
error.

  ...
  Compiling cupsaddsmb.c...
  Linking cupsaddsmb...
  Compiling cupstestppd.c...
  cupstestppd.c: In function `main':
  cupstestppd.c:100: warning: implicit declaration of function`ppdSetConformance'
  cupstestppd.c:100: error: `PPD_CONFORM_STRICT' undeclared (first use in this function)
  cupstestppd.c:100: error: (Each undeclared identifier is reported only once
  cupstestppd.c:100: error: for each function it appears in.)
  cupstestppd.c:125: error:`PPD_CONFORM_RELAXED' undeclared (first use in this function)
  make[1]: **\* [cupstestppd.o] Error 1
  make: **\* [all] Error 1

I configured like this,

  export LDFLAGS="-L/usr/local/lib"
  export CPPFLAGS="-I /usr/local/include"

  ./configure
