### ISSUE TITLE
"gdevcups.c" will not build with GCC-3.3

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#161]
Version: 7.05.6
CUPS.org User: tyrerj.acm

I am unable to build ESP GhostScript or to try the device in the current version of GhostScript.

gcc `cat ./obj/cc.tr`  -DHAVE_MKSTEMP -O2 -march=k6-3 -mcpu=k6-3 -Wall -Wstrict-prototypes -Wmissing-declarations -Wmissing-prototypes -fno-builtin -fno-common  -DGX_COLOR_INDEX_TYPE='unsigned long long' -I./obj -I./src  -o ./obj/gdevcups.o -c pstoraster/gdevcups.c
pstoraster/gdevcups.c:879: error: conflicting types for `cups_map_cmyk_color'
pstoraster/gdevcups.c:124: error: previous declaration of`cups_map_cmyk_color'
pstoraster/gdevcups.c:1259: error: conflicting types for `cups_map_rgb_color'
pstoraster/gdevcups.c:126: error: previous declaration of`cups_map_rgb_color'
pstoraster/gdevcups.c: In function `cups_print_pages':
pstoraster/gdevcups.c:1857: warning: implicit declaration of function`gs_exit'
pstoraster/gdevcups.c: In function `cups_set_color_info':
pstoraster/gdevcups.c:2410: warning: assignment from incompatible pointer type
make: **\* [obj/gdevcups.o] Error 1
