### ISSUE TITLE
error: 'mallinfo_time' undeclared

### ISSUE THREAD

**Issue by rohieb** [apple/cups#5051]
Building with `./configure --enable-mallinfo` currently fails in `scheduler/main.c`:

```
main.c: In function 'select_timeout':
main.c:1760:39: error: 'mallinfo_time' undeclared (first use in this function)
   if (LogLevel >= CUPSD_LOG_DEBUG && (mallinfo_time + 60) < timeout)
                                       ^
```

A short git bisect shows that the corresponding declaration of `mallinfo_time` was removed or renamed in 5bd77a735f888 without further comment (probably lost in git-to-svn migration).

**Comment by michaelrsweet** [comment]
OK, looks like the implementation was changed to only report this once a minute, but not to wake up for it. Fix is to not set the select timeout based on mallinfo_time anymore...

[master 13be9452d] Fix a build issue with `--enable-mallinfo` (Issue #5051)

**Comment by rohieb** [comment]
Thank you!
